[package]
name = "bytecode_test"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecode = {path="../bytecode"}
seq-macro = "0.3.0"