[package]
name = "bytecode_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecode = {path="../bytecode"}
seq-macro = "0.2.2"