on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.56.1, 1.57.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt clippy
      - run: cargo build
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check clippy lints
        run: cargo clippy --all-targets --all-features -- -D warnings
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.56.1, 1.57.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run tests
        run: cargo test --all --all-features --no-fail-fast
